### ISSUE TITLE
Pipeline Serialization

### ISSUE THREAD

**Issue by hanjunlee** [gitploy-io/gitploy#368]
It is necessary to prevent deployment to the same runtime environment simultaneously. If another deployment is in progress when a deployment is triggered, users may be confused.

To implement, when a deployment is requested, it returns a failure response if another deployment for the same environment is in progress. 

Ex)
```yaml
envs:
  - name: prod
    serialization: true
```
