### ISSUE TITLE
Input `payload` dynamically when a user deploy

### ISSUE THREAD

**Issue by hanjunlee** [gitploy-io/gitploy#377]
Dynamic `payload` provides users with flexible deployment. For example, if a user has multiple deployment strategies, you can choose a specific deployment strategy for deployment.

The implementation is such that the configuration file includes the definition of the dynamic payload like below: 

```yaml
dynamic_payload:
  enabled: true
  inputs:
    strategy:
      description: 'Deploy Strategy'     
      required: true
      default: 'default' 
      type: select
      options:
      - default
      - canary
      - blue-green
    canary-weight:
      description: 'Canary Weight'
      required: false 
      default: 5
      type: number
```
